In [1]:
import numpy as np
import torch

In [2]:
data = [[3,5,20], [10, 5, 50], [1, 5, 10]]
x_data = torch.tensor(data)

In [3]:
x_data[1:]

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [4]:
x_data.flatten()

tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [5]:
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [6]:
x_data.shape

torch.Size([3, 3])

In [7]:
x_data.dtype

torch.int64

In [8]:
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]], dtype=int64)

In [9]:
a = torch.zeros(3,2)
b = a.view(2,3)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [10]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
d = torch.zeros(3,2)
c = d.t().reshape(6)
d.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [12]:
c

tensor([0., 0., 0., 0., 0., 0.])

In [13]:
data = [[[1,2,3], [2,3,4]]]
data = torch.Tensor(data)

In [14]:
data.shape

torch.Size([1, 2, 3])

#### Tensor 연산 
##### 행렬곱셈 연산은 함수 mm을 사용한다. 

In [15]:
a.mm(b)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [16]:
a.matmul(b)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [17]:
x = [[[1,2], [0,1]],
    [[0,-1], [-1,-2]]]
x = torch.Tensor(x)

In [18]:
x

tensor([[[ 1.,  2.],
         [ 0.,  1.]],

        [[ 0., -1.],
         [-1., -2.]]])

In [19]:
b = [3, 7]
b = torch.Tensor(b)

In [20]:
x.matmul(b)

tensor([[ 17.,   7.],
        [ -7., -17.]])

#### 인덱싱 : 원하는 부분의 데이터 가져오기 
#### torch.index_select(input, dim, index, *, out=None)

In [21]:
A = torch.Tensor([[1, 2],
                  [3, 4]])
#A행렬을 벡터로 flatten 시켜준다. 
A = A.view(4)
# >> A = [1,2,3,4]
indices = torch.tensor([0,2])
# 인덱스 0, 2를 가리킴. 
torch.index_select(A, 0, indices)
# input : A, dim 0에서 idx 0, 2를 선택함. 

tensor([1., 3.])

In [22]:
A

tensor([1., 2., 3., 4.])

#### 대각선 인덱싱
#### torch.gather(input, dim, index)

In [23]:
A = torch.Tensor([[1, 2],
                  [3, 4]])

A = torch.gather(A, 1, torch.tensor([[0, 0], [1, 0]]))
A = A.view(4)
indices = torch.tensor([0,2])
torch.index_select(A, 0, indices)

tensor([1., 4.])

In [24]:
A = torch.Tensor([[[1, 2],
                   [3, 4]],
                  [[5, 6],
                   [7, 8]]])

# torch.gather 함수를 써서 해보세요!
A = torch.gather(A, 2, torch.tensor([[[0, 1], [1,0]], [[0,1],[1, 0]]]))
A = A.view(4,2)
t = A.transpose(0, 1)
t[0].view(2,2)

tensor([[1., 4.],
        [5., 8.]])

#### 함수정리
##### torch.from_numpy(input) : numpy 자료형에서 tensor로 변환
##### torch.zeros(dim) : 영행렬 만듦
##### torch.zeros_like(input) : input의 원소를 0으로 변환

In [25]:
# 🦆 torch.from_numpy
a = np.array([1,2,3])
t = torch.from_numpy(a)
t

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
# 🦆 torch.zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [27]:
t = torch.empty(2,3)

In [28]:
# 🦆 torch.zeros_like
torch.zeros_like(t)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### 선형대수 Basic 연산
##### torch.addmm(input, m1, m2) : input에 m1과 m2의 mm 결과를 더한다. 

In [32]:
M = torch.randn(2, 3)
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.addmm(M, mat1, mat2)

tensor([[-0.9664, -0.1740, -0.1761],
        [-0.8625, -0.4686, -1.1726]])

In [33]:
# 🦆 torch.eye(n) : nxn의 I행렬
a = torch.eye(10)
torch.matrix_rank(a)

tensor(10)

### CLASS  torch.nn.Linear(in_features, out_features, bias=True, device=None, dtype=None)

##### Parameters
##### in_features – size of each input sample

##### out_features – size of each output sample

##### bias – If set to False, the layer will not learn an additive bias. Default: True

In [34]:
from torch import nn

X = torch.Tensor([[1, 2],
                  [3, 4]])
#  nn.Linear를 사용해서 (2, 5)로 크기를 바꾸고 크기를 출력한다.
m = nn.Linear(2,5)
m(X).size()

torch.Size([2, 5])

#### nn.identity
##### Residual block에서 사용되는 이유 : 아마 Residual block 에서 shorcut을 통해 레이어의 input 이 다음 레이어의 input과 더해지는데, 이때 indentity()를 사용해서 input값을 보존하려고 사용하는 것 같다. 

In [35]:
m = nn.Identity()
print(m(X))

tensor([[1., 2.],
        [3., 4.]])
