In [1]:
import torch
from torch import nn

### nn.Sequential 은 순서대로 실행하고, nn.ModuleList 는 각 모듈을 list로 인덱싱한다. 

In [2]:
class Add(nn.Module):
    def __init__(self, value):
        super().__init__()
        self.value = value

    def forward(self, x):
        return x + self.value

In [3]:
calculator = nn.Sequential(
    Add(3),
    Add(2),
    Add(5)
)

x = torch.tensor([1])
output_seq = calculator(x)

In [4]:
class Calculator(nn.Module):
    def __init__(self):
        super().__init__()
        self.add_list = nn.ModuleList([Add(2), Add(3), Add(5)])

    def forward(self, x):
        x = self.add_list[1](x)
        x = self.add_list[0](x)
        x = self.add_list[2](x)
        return x

In [5]:
y = torch.tensor([1])

calculator = Calculator()
output_mlst = calculator(y)
print(output_mlst)

tensor([11])


In [6]:
class Calculator(nn.Module):
    def __init__(self):
        super().__init__()
        self.add_dict = nn.ModuleDict({'add2': Add(2),
                                       'add3': Add(3),
                                       'add5': Add(5)})

    def forward(self, x):
        x = self.add_dict['add3'](x)
        x = self.add_dict['add2'](x)
        x = self.add_dict['add5'](x)
        return x

In [7]:
x = torch.tensor([1])
calculator = Calculator()
output = calculator(x)
output

tensor([11])

### Parameter; Autograd 기능을 사용하기 위해서 파라미터로 저장하고 토치에서 트랙킹한다. 

In [8]:
import torch
from torch import nn
from torch.nn.parameter import Parameter


class Linear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()

        self.W = torch.ones(3,2)
        self.b = torch.ones(1)

    def forward(self, x):
        output = torch.addmm(self.b, x, self.W.T)

        return output

In [9]:
x = torch.Tensor([[1, 2],
                  [3, 4]])

linear = Linear(2, 3)
output = linear(x)
output

tensor([[4., 4., 4.],
        [8., 8., 8.]])

### Tensor, Parameter, Buffer 의 차이점 
##### Parameter로 지정하지 않아서 값이 업데이트 되지 않는다 해도 저장하고싶은 tensor가 있을 때 Buffer를 사용한다. 
##### Parameter는 아니어도, model의 상태를 나타내는 값이기 때문이다. 

In [ ]:
- "Tensor"
    - ❌ gradient 계산
    - ❌ 값 업데이트
    - ❌ 모델 저장시 값 저장
- "Parameter"
    - ✅ gradient 계산
    - ✅ 값 업데이트
    - ✅ 모델 저장시 값 저장
- "Buffer"
    - ❌ gradient 계산
    - ❌ 값 업데이트
    - ✅ 모델 저장시 값 저장

In [10]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()

        self.parameter = Parameter(torch.Tensor([7]))
        self.tensor = torch.Tensor([7])

        # orch.Tensor([7])를 buffer에 저장
        self.register_buffer('buffer', torch.Tensor([7]))

In [13]:
# parameter와 함께 buffer도 저장됨.
model = Model()
model.state_dict()

OrderedDict([('parameter', tensor([7.])), ('buffer', tensor([7.]))])